### ISSUE TITLE
Reading Database config from database.yml

### ISSUE THREAD

**Issue by dombarnes** [DatabaseCleaner/database_cleaner#709]
In my test environment, I want to read my test DB from a different environment variable, `TEST_DATABASE_URL` so I've set this in my database.yml file
```
test:
  <<: *default
  adapter: postgresql
  url: <%= ENV["TEST_DATABASE_URL"] %>
```
However this causes failures in my test spec run
```
Failure/Error:
        DatabaseCleaner.cleaning do
          example.run
        end

      ActiveRecord::ConnectionNotEstablished:
        connection to server at "::1", port 5432 failed: FATAL:  role "root" does not exist
```
